for testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - main
+      - niks
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -19,22 +20,33 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
-
+# create env file and install npm dependencies
       - name: Create .env file Backend
         run: |
+         if [ ${{ github.ref }} == 'refs/heads/dev' ]; then
           echo "$DEV_ENV" >> ${{ github.workspace }}/TBS-Gamification-dev/games-and-quizzes/empty-returns/.env
+          cd ${{ github.workspace }}/TBS-Gamification-dev/games-and-quizzes/empty-returns/ && npm install
+         elif [ ${{ github.ref }} == 'refs/heads/stag' ]; then
+          echo "$STAG_ENV" >> ${{ github.workspace }}/TBS-Gamification-dev/games-and-quizzes/empty-returns/.env
+          cd ${{ github.workspace }}/TBS-Gamification-dev/games-and-quizzes/empty-returns/ && npm install
+          else          
+            echo "not working properly"
+            exit 1
+          fi
         shell: bash
         env:
           DEV_ENV: ${{ secrets.ENV_FILE_DEV }}
-
-      - name: Install dependencies
-        run: cd ${{ github.workspace }}/TBS-Gamification-dev/games-and-quizzes/empty-returns/ && npm install
-
+          STAG_ENV: ${{ secrets.ENV_FILE_DEV }}
+  # create build         
       - name: Build
         run: |
+          if [ ${{ github.ref }} == 'refs/heads/dev' ]; then
             cd ${{ github.workspace }}/TBS-Gamification-dev/games-and-quizzes/empty-returns/ && npx webpack --mode production
-            pwd
-            ls -la
+          elif [ ${{ github.ref }} == 'refs/heads/stag' ]; then
+            cd ${{ github.workspace }}/TBS-Gamification-dev/games-and-quizzes/empty-returns/ && npx webpack --mode production
+          else
+            exit 1
+          fi
 #      - name: Tar files
  #       run: tar -cvf dist.tar /home/runner/work/New_repo/New_repo/TBS-Gamification-dev/games-and-quizzes/empty-returns/*
       - name: Upload Artifact
@@ -57,15 +69,15 @@ jobs:
   #          tree /home/runner/work/New_repo/New_repo
    #         sudo cp -Rf TBS-Gamification-dev/games-and-quizzes/empty-returns/* TBS-Gamification-dev/games-and-quizzes/
     #        cd vaibhav
-      - name: Download Artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: Archive artifact
-          path: |
-            /home/runner/work/New_repo/New_repo/
-            pwd
-            ls -la
-            tree
+#      - name: Download Artifact
+ #       uses: actions/download-artifact@v2
+  #      with:
+   #       name: Archive artifact
+    #      path: |
+     #       /home/runner/work/New_repo/New_repo/
+      #      pwd
+       #     ls -la
+        #    tree
 #  Deployment:
  #     runs-on: ubuntu-latest
   #    needs: build 
@@ -75,11 +87,19 @@ jobs:
         env: # Or as an environment variable
           WPE_SSHG_KEY_PRIVATE1: ${{ secrets.WPE_SSHG_KEY_PRIVATE1 }}
           STAG: pluginsuppostg
+          PROD: tbsgameprod
         run: |
           BRANCH_NAME=${GITHUB_REF#refs/heads/}
           cd $GITHUB_WORKSPACE
           git checkout $BRANCH_NAME
-          if [ $BRANCH_NAME == "main" ]; then DEPLOY=${STAG}; else exit; fi
+          if [ $BRANCH_NAME == "main" ]; then
+            DEPLOY=${STAG}
+          elif [ $BRANCH_NAME == "niks" ]; then
+            DEPLOY=${PROD}                      
+          else
+            echo "Branch not found."
+            exit 1
+          fi          
           mkdir ~/.ssh
           echo $WPE_SSHG_KEY_PRIVATE1 | base64 --decode >> ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
